import type { Locale } from './config';

// Labels describe real profile information, rather than fictional RPG abilities.
export const statusCopy: Record<Locale, {
  party: string; status: string; name: string; role: string; activity: string; activityValue: string;
  developer: string; listener: string; species: string; bird: string;
  speech: string; kansai: string; select: string;
}> = {
  ja: { party: 'パーティー', status: 'ステータス', name: 'なまえ', role: '役割', activity: '活動', activityValue: 'ブラウザーゲーム・iOSアプリの開発', developer: '個人ゲーム開発者', listener: 'ゲーム紹介の聞き役', species: '種族', bird: 'シマエナガ', speech: '話し方', kansai: '関西弁', select: 'キャラを選ぶ' },
  en: { party: 'Party', status: 'Status', name: 'Name', role: 'Role', activity: 'Activity', activityValue: 'Browser games and iOS apps', developer: 'Independent game developer', listener: 'Game introduction partner', species: 'Species', bird: 'Long-tailed tit', speech: 'Speech', kansai: 'Kansai dialect', select: 'Choose a character' },
  'zh-cn': { party: '队伍', status: '状态', name: '名字', role: '角色', activity: '活动', activityValue: '浏览器游戏与 iOS 应用开发', developer: '独立游戏开发者', listener: '游戏介绍的提问搭档', species: '种族', bird: '银喉长尾山雀', speech: '说话方式', kansai: '关西方言', select: '选择角色' },
  'zh-tw': { party: '隊伍', status: '狀態', name: '名字', role: '角色', activity: '活動', activityValue: '瀏覽器遊戲與 iOS App 開發', developer: '獨立遊戲開發者', listener: '遊戲介紹的提問搭檔', species: '種族', bird: '銀喉長尾山雀', speech: '說話方式', kansai: '關西方言', select: '選擇角色' },
  ko: { party: '파티', status: '상태', name: '이름', role: '역할', activity: '활동', activityValue: '브라우저 게임 및 iOS 앱 개발', developer: '개인 게임 개발자', listener: '게임 소개의 질문 담당', species: '종족', bird: '흰머리오목눈이', speech: '말투', kansai: '간사이 사투리', select: '캐릭터 선택' },
  es: { party: 'Equipo', status: 'Estado', name: 'Nombre', role: 'Rol', activity: 'Actividad', activityValue: 'Juegos de navegador y apps para iOS', developer: 'Desarrollador independiente', listener: 'Compañero de presentación', species: 'Especie', bird: 'Mito de cola larga', speech: 'Habla', kansai: 'Dialecto de Kansai', select: 'Elige un personaje' },
  fr: { party: 'Équipe', status: 'Statut', name: 'Nom', role: 'Rôle', activity: 'Activité', activityValue: 'Jeux sur navigateur et applications iOS', developer: 'Développeur indépendant', listener: 'Partenaire de présentation', species: 'Espèce', bird: 'Mésange à longue queue', speech: 'Parler', kansai: 'Dialecte du Kansai', select: 'Choisir un personnage' },
  de: { party: 'Gruppe', status: 'Status', name: 'Name', role: 'Rolle', activity: 'Aktivität', activityValue: 'Browserspiele und iOS-Apps', developer: 'Unabhängiger Spieleentwickler', listener: 'Partner bei Spielvorstellungen', species: 'Art', bird: 'Schwanzmeise', speech: 'Sprache', kansai: 'Kansai-Dialekt', select: 'Figur auswählen' },
  'pt-br': { party: 'Equipe', status: 'Status', name: 'Nome', role: 'Função', activity: 'Atividade', activityValue: 'Jogos de navegador e apps para iOS', developer: 'Desenvolvedor independente', listener: 'Parceiro de apresentação', species: 'Espécie', bird: 'Chapim-rabilongo', speech: 'Fala', kansai: 'Dialeto de Kansai', select: 'Escolha um personagem' },
};


export const characterCopy: Record<Locale, {
  job: string; skill: string; companion: string; quest: string;
  jobs: [string, string]; skills: [string, string]; descriptions: [string, string];
}> = {
  ja: { job: 'ジョブ', skill: 'とくぎ', companion: 'なかま', quest: '挑戦中のクエスト', jobs: ['ゲームクリエイター', 'ツッコミ役'], skills: ['思いつきをゲームにする', '気になることを聞く'], descriptions: ['思いついたアイデアをゲームにするクリエイター。ブラウザーゲームやiOSアプリを作っている。相棒のおナガとともに、このサイトで自作ゲームを紹介する。', 'あかおの相棒のシマエナガ。気になることは遠慮なく聞く、関西弁のツッコミ役。あかおのゲーム紹介に付き合っている。'] },
  en: { job: 'Class', skill: 'Talent', companion: 'Companion', quest: 'Current quest', jobs: ['Game creator', 'Straight man'], skills: ['Turning ideas into games', 'Asking what is on his mind'], descriptions: ['A creator who turns ideas into games. He makes browser games and iOS apps, and introduces his creations on this site alongside his companion Onaga.', 'Akao’s long-tailed tit companion. The Kansai-speaking straight man who never holds back a question. He joins Akao for the game introductions.'] },
  'zh-cn': { job: '职业', skill: '特长', companion: '伙伴', quest: '挑战中的任务', jobs: ['游戏创作者', '吐槽担当'], skills: ['把点子做成游戏', '问出好奇的问题'], descriptions: ['把点子变成游戏的创作者。制作浏览器游戏与 iOS 应用，和伙伴 Onaga 一起在本站介绍自己的游戏。', 'Akao 的银喉长尾山雀伙伴。说关西方言的吐槽担当，有好奇的问题就毫不客气地问。他陪 Akao 一起介绍游戏。'] },
  'zh-tw': { job: '職業', skill: '特長', companion: '夥伴', quest: '挑戰中的任務', jobs: ['遊戲創作者', '吐槽擔當'], skills: ['把點子做成遊戲', '問出好奇的問題'], descriptions: ['把點子變成遊戲的創作者。製作瀏覽器遊戲與 iOS App，和夥伴 Onaga 一起在本站介紹自己的遊戲。', 'Akao 的銀喉長尾山雀夥伴。說關西方言的吐槽擔當，有好奇的問題就毫不客氣地問。他陪 Akao 一起介紹遊戲。'] },
  ko: { job: '직업', skill: '특기', companion: '동료', quest: '도전 중인 퀘스트', jobs: ['게임 크리에이터', '태클 담당'], skills: ['아이디어를 게임으로 만들기', '궁금한 것을 물어보기'], descriptions: ['떠오른 아이디어를 게임으로 만드는 크리에이터. 브라우저 게임과 iOS 앱을 만들며, 동료 오나가와 함께 이 사이트에서 자신의 게임을 소개한다.', '아카오의 동료인 흰머리오목눈이. 궁금한 것은 거리낌 없이 묻는 간사이 사투리의 태클 담당. 아카오의 게임 소개에 함께한다.'] },
  es: { job: 'Clase', skill: 'Talento', companion: 'Compañero', quest: 'Misión actual', jobs: ['Creador de juegos', 'Contrapunto cómico'], skills: ['Convertir ideas en juegos', 'Preguntar lo que le intriga'], descriptions: ['Un creador que convierte ideas en juegos. Desarrolla juegos de navegador y apps para iOS, y presenta sus creaciones en este sitio junto a su compañero Onaga.', 'El mito de cola larga que acompaña a Akao. Habla en dialecto de Kansai y hace de contrapunto cómico, preguntando sin reservas lo que le intriga. Acompaña a Akao en las presentaciones de juegos.'] },
  fr: { job: 'Classe', skill: 'Talent', companion: 'Compagnon', quest: 'Quête en cours', jobs: ['Créateur de jeux', 'Partenaire de répartie'], skills: ['Transformer les idées en jeux', 'Poser les questions qui intriguent'], descriptions: ['Un créateur qui transforme ses idées en jeux. Il réalise des jeux sur navigateur et des applications iOS, puis présente ses créations sur ce site avec son compagnon Onaga.', 'Le compagnon d’Akao, une mésange à longue queue. Il parle le dialecte du Kansai et pose ses questions sans détour, avec un sens de la répartie. Il accompagne Akao dans ses présentations de jeux.'] },
  de: { job: 'Klasse', skill: 'Talent', companion: 'Gefährte', quest: 'Aktuelle Quest', jobs: ['Spieleentwickler', 'Schlagfertiger Partner'], skills: ['Ideen in Spiele verwandeln', 'Neugierige Fragen stellen'], descriptions: ['Ein Entwickler, der Ideen in Spiele verwandelt. Er entwickelt Browserspiele und iOS-Apps und stellt seine Werke auf dieser Seite zusammen mit seinem Gefährten Onaga vor.', 'Akaos Gefährte, eine Schwanzmeise. Er spricht Kansai-Dialekt, stellt unverblümt neugierige Fragen und gibt schlagfertige Antworten. Er begleitet Akao bei den Spielvorstellungen.'] },
  'pt-br': { job: 'Classe', skill: 'Talento', companion: 'Companheiro', quest: 'Missão atual', jobs: ['Criador de jogos', 'Contraponto cômico'], skills: ['Transformar ideias em jogos', 'Perguntar o que desperta curiosidade'], descriptions: ['Um criador que transforma ideias em jogos. Desenvolve jogos de navegador e apps para iOS e apresenta suas criações neste site junto de seu companheiro Onaga.', 'O chapim-rabilongo companheiro de Akao. Fala no dialeto de Kansai e faz o contraponto cômico, perguntando sem receio o que desperta sua curiosidade. Acompanha Akao nas apresentações dos jogos.'] },
};
